language: node_js

matrix:
  include:
    - os: linux
      dist: xenial
      sudo: required
    - os: osx
      osx_image: xcode10.1

cache:
  yarn: true

notifications:
  email: false

branches:
  only:
    - master
    - development

node_js:
  - "10"

services:
  - docker

env:
  global:
    - NODE_ENV=test

# install:
#   - yarn
# before_script:
#   - yarn lint
#   - ./dockers/start.sh
#   - node ./scripts/install.js
script:
  - bash scripts/ci-setup.sh
